spin_manifest_version = 2

[application]
name = "test"
version = "0.1.0"
authors = ["karthik2804 <karthik.ganeshram@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "test"

[component.test]
source = "app.wasm"
allowed_outbound_hosts = []
[component.test.build]
command = "componentize-py -d ../../wit -w spin componentize app -o app.wasm"
